"""Add token blocklist model

Revision ID: 235556dbc375
Revises: d5fed03c8e7e
Create Date: 2024-06-27 23:06:02.644108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235556dbc375'
down_revision = 'd5fed03c8e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
